### ISSUE TITLE
onbeforeunload prompt text and buttons

### ISSUE THREAD

**Issue by TimOPI** [The-Ambit-Group/school-meals#117]
We're interested in having a more informative onbeforeunload prompt:

![reloadprompt](https://cloud.githubusercontent.com/assets/22204672/20639078/80144eae-b387-11e6-8f01-f004ec31efed.png)

Ideally, the prompt would function the same across browsers.

Text for copy/paste or if image doesn't load properly;

Do you want to leave the application?

If you would like to go back to the previous page in the application, click "Stay," and use the "Back" button on the bottom of the screen.

(buttons)
[Leave]  [Stay]

**Comment by ambit-developer** [comment]
Browsers keep this locked down as a security measure (to ensure that users can leave a website without being tricked into staying, etc.).

There's light wiggle room to customize the message, but it's not advisable because not all browsers respect it (leading to fragmentation), buttons say different things in different browsers (so it's hard to program a custom message that references the button text), and the native browser message translation is handled natively by the browser.

See #2 for some example screenshots.

**Comment by RichardDudek** [comment]
The Dev Team advises against piercing the standard browser public API - unfortunately, this type of modification would put us  on that slippery slope of having to address various issues with the multitudes of browser/device combinations.  Perhaps for V2.0 we can keep this CR in backlog for consideration.

There are a lot of uncontrollable side effects that could impact the user experience beyond the impersonal and non-instructive default browser message that is the subject of this CR item.

**Comment by RichardDudek** [comment]
Might be of more value to the users if we urged them to open a new browser session window to run the NSLP tool and advise that they ONLY use the application controls as opposed  to the browser controls while running the application.  But then the WELCOME page starts to look like a legal document :-(

**Comment by TimOPI** [comment]
@ambit-developer @RichardDudek We agree with your recommendation not to change the browser warning.
