### ISSUE TITLE
Screen occasionally disappears

### ISSUE THREAD

**Issue by ambit-developer** [The-Ambit-Group/school-meals#31]
> In Safari and in IE, occasionally the entire screen disappears. (See screen shot below.)

<img width="1088" alt="screen shot 2016-11-08 at 8 21 47 am" src="https://cloud.githubusercontent.com/assets/23132316/20100653/717e2e4a-a58c-11e6-886e-55492f17e0dc.png">

**Comment by rcoop017** [comment]
Not only in Sarfari or IE, can be generated in all browsers.

 We believe that we are triggering a separate dead page via the radio buttons due to the foster status of a single student household:
o   Our scenario:
§  Welcome: get started;
§  Before you begin: continue;
§  Attestation:
·         First name: John;
·         Last name: Doe;
·         Continue;
§  Student:
·         First name: Susie;
·         Last name: Doe;
·         Continue;
§  Assistance program: none; continue;
§  Foster status for Susie (one student household): no;
§  HMR:
·         Clicking in the lower ¼ of the No buttons selects “No”;
·         Clicking in the lower ¼ of the Yes buttons selections “Yes”; but
·         Clicking in the upper ¾ of the Yes buttons blanks the page;
§  Use the navigation bar to return to “Students”;
§  Student: continue;
§  Assistance program: none; continue;
§  Foster status for Susie is now set to yes (not selected by user)
o   This swapping from no to yes invalidates the HMR page; therefore blanking the user’s current page
o   You can also view the “Data” tab to validate that the “isFoster” status for Susie changes from “false” to “true”
·         We believe that we are triggering a change in foster status for a multiple foster student household:
o   Our scenario:
§  Welcome: get started;
§  Before you begin: continue;
§  Attestation:
·         First name: John;
·         Last name: Doe;
·         Continue;
§  Student:
·         First name: Susie;
·         Last name: Doe;
·         Add student:
·         First name: Tom;
·         Last name: Doe;
·         Continue;
§  Assistance program: none; continue;
§  Foster status:
·         Yes (enabling check boxes)
·         Susie: Yes
·         Tom: No
§  HMR:
·         The page only asks questions about Tom: “Does Tom receive…”
·         Clicking in the lower ¼ of the No buttons selects “No”;
·         Clicking in the lower ¼ of the Yes buttons selections “Yes”; but
·         Clicking in the upper ¾ of the No button changes the questions to read “Do Susie or Tom receive…”
§  Use the Application back button to navigate back to the foster screen
§  Foster status for both Susie and Tom are now set to no (not selected by user)
o   This swapping from yes to no removes the correctly reported foster status for Susie
o   You can also view the “Data” tab to validate that the “isFoster” status for Susie changes from “true” to “false”
 
Additionally, as shown in the video, there are odd selection areas for the yes and no radio buttons.  These areas differ by browser, but hovering over the buttons in the upper ¾ area (noted above) shows the cursor as a pointer hand rather than the standard point (hovering in the button ¼ of the buttons shows the standard cursor.)

**Comment by ambit-developer** [comment]
I can reproduce. Taking it.

**Comment by TimOPI** [comment]
5998988 adds concat back in (this.name + '-true').  Tried this concat earlier, and got errors related to SummaryPersonCollectionItem but changes in f2b0cf5 may be the cause of the error no longer occurring.

**Comment by ambit-developer** [comment]
@TimOPI — you nailed it.

The "Yes" HMR labels were being applied to the foster radio button because of the bug preventing unique ID creation.
