### ISSUE TITLE
Apply USDS “text input error” functionality

### ISSUE THREAD

**Issue by ambit-developer** [The-Ambit-Group/school-meals#35]
1. apply U.S. Digital Design Standard functionality when required fields are left blank (currently the application just disables the “Continue” button.
2. apply industry standard masking to telephone numbers (allowing 7 or 10 digits) and zip codes (allowing 5 or 9 digits)

**Comment by RichardDudek** [comment]
Hey Ross, Blake and Bryan –

We had our phone call with Ed & Tim tonight regarding the message Ed sent today:
It sounds terrible for me to ask, but what do you think it would take to pull off #35 on the “open issues” list?
User feedback is that we really need to explain why the continue button is disabled when required fields are missing.  The solution we proposed was to follow the way that USDS handles this.  But there may be a simpler way.  Let’s discuss sometime today.
Here is what we were able to negotiate:

1.	The application will remain functionally unchanged because it does comply with USDS standards … disabled buttons are “okay”
2.	Ambit Dev Team will add the following to all screens which have Continue buttons which are only enabled once all Required fields are populated:
a.	Place an asterisk (*) to the upper right-hand corner of the Continue button (for now it should be in red)
b.	Place the following text (immediately to the right of the Continue button):
                  *The Continue button will be ENABLED once all Required fields have been entered

This will apply to all screens that have Continue buttons that are disabled until Required fields are populated.

**Comment by RichardDudek** [comment]
Please let me know how many hours this would take … here are my thoughts regarding the steps:

1.	Add asterisk (static text) to the right of all Continue buttons on all screens with disabled Continue buttons that become enabled once Required data fields are all populated
2.	Add text (via object) to all screens with disabled Continue buttons that become enabled once Required data fields are all populated
3.	Add localization code to allow for translation of the message
4.	Add text object to EMPTY.json file 

Please let me know if I missed anything.
