### ISSUE TITLE
Add "Edit" button next to every Adult's Name

### ISSUE THREAD

**Issue by rcoop017** [The-Ambit-Group/school-meals#99]
The summary screen doesn’t offer “edit” buttons next to the adults’ names.  It does have edit buttons next to each income source, which is great).

Adding a single edit button next to “Adults” is not the best solution though, since the attestor and the “other adults” are on different pages.  So, our recommended fix is to add an edit button next to every adult’s name.  The edit button next to the attestor would take you back to the “I certify” screen.  The edit button next to any one of the other adults would take you back to the “Other adults” screen.  (It’s OK with us if you always land at the top of the “Other adults” screen even if you hit edit next to the third “Other adult.”

**Comment by ambit-developer** [comment]
Two questions:

1. Leave or mix the "master" edit button in the adults heading?

2. Any concern that the UI may look unbalanced between adults wit edit links and children without them?

**Comment by ambit-developer** [comment]
`s/mix/nix/`

**Comment by ambit-developer** [comment]
Fixed with 9708baef64a75fb23ca5151544bc55ba24cc04fd and the few surrounding commits.

Links to the adults' income overview pages, which we didn't previously have links to and would probably be helpful. Those pages, in turn, also have new links back to the attester/adults pages. Hopefully this is a best all around solution.
